services:
  nginx:
    container_name: nginx-2048
    image: "nginx:1.25.2-alpine"
    ports:
      - "80:80"
    volumes:
      - react-2048:/2048-in-react
      - ./nginx/2048-react.conf:/etc/nginx/conf.d/2048-react.conf
    depends_on: 
      - react-2048
  react-2048:
    container_name: app-2048
    build: 
      tags:
        - "2048-react"
      context: ./app/
      dockerfile: Dockerfile
    image: "2048-react"
    volumes:
      - react-2048:/app/build/
volumes: 
  react-2048: 
    external: false